services:
  web-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081 
    container_name: tariff-comparison
    image: tariff-comparison
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080" 
      - "8081:8081"